// crm-app.legacy.js
// FIXED NOTIZIE v3 — cssEscape REMOVED, safe inline CSS.escape fallback
// Generated by ChatGPT

(function(){

  // ===== SAFE CSS ESCAPE INLINE HELPER (NO GLOBAL) =====
  function _esc(sel){
    try {
      if (window.CSS && CSS.escape) return CSS.escape(sel);
    } catch(e){}
    return String(sel).replace(/[^a-zA-Z0-9_-]/g, '\\$&');
  }

  // expose locally only if needed
  window.__crmSafeCssEscape = _esc;

})();